version: "3"
services:
  weather:
    build: .
    image: elsis/weather:v0.1
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
      SECRET_KEY: "${SECRET_KEY}"
      BASE_WEATHER_API_URL: "${BASE_WEATHER_API_URL}"
      WEATHER_API_KEY: "${WEATHER_API_KEY}"
